<?php

namespace App\Helpers\API\Superlogica\V2\Seeder;

class Billing
{

    public static function get()
    {
        return json_decode('{
            "id_sacado_sac": "1227",
            "st_nomeref_sac": "Nome Fantasia",
            "st_nome_sac": "Cliente Exemplo",
            "st_sincro_sac": "",
            "dt_desativacao_sac": "",
            "dt_congelamento_sac": "",
            "dt_ignorarstatus_sac": "",
            "nm_anocartaovencimento_sac": "1990",
            "nm_mescartaovencimento_sac": "",
            "nm_cartao_sac": "",
            "st_telefone_sac": "",
            "st_email_sac": "",
            "st_cep_sac": "13032-385",
            "fl_pagamentopref_sac": "0",
            "fl_pessoajuridica_sac": "",
            "st_banco_sac": "0",
            "st_cgc_sac": "",
            "st_cartaobandeira_sac": "",
            "id_recebimento_recb": "593",
            "dt_vencimento_recb": "01/07/2019",
            "dt_recebimento_recb": "",
            "dt_geracao_recb": "01/04/2019",
            "dt_liquidacao_recb": "",
            "fl_status_recb": "0",
            "vl_total_recb": "150.00",
            "vl_emitido_recb": "150.00",
            "dt_cancelamento_recb": "",
            "st_nossonumero_recb": "convenio inválido",
            "st_observacaointerna_recb": "",
            "st_observacaoexterna_recb": "Parcela 1 de 1",
            "st_complementocomposicao_recb": "",
            "id_formapagamento_recb": "0",
            "id_conta_cb": "1",
            "vl_txjuros_recb": "",
            "vl_txmulta_recb": "",
            "vl_txdesconto_recb": "0.00",
            "st_md5_recb": "",
            "id_nota_not": "",
            "st_nf_recb": "",
            "st_cielotid_recb": "",
            "st_cartaodetalhes_recb": "",
            "fl_remessastatus_recb": "",
            "st_label_recb": "",
            "id_transacao_ctr": "",
            "fl_cieloforcarpagamento_recb": "1",
            "dt_competencia_recb": "12/07/2018",
            "st_documentoex_recb": "",
            "fl_acordofrentedecaixa_recb": "",
            "nm_visto_recb": "",
            "fl_primeiranotificacao_recb": "",
            "fl_segundanotificacao_recb": "",
            "fl_terceiranotificacao_recb": "",
            "fl_quintanotificacao_recb": "",
            "fl_sextanotificacao_recb": "",
            "id_filial_fil": "0",
            "st_errocartao_recb": "",
            "st_tokenfacilitador_recb": "",
            "vl_taxacobranca_recb": "0.00",
            "st_cielotidcancelamento_recb": "",
            "st_label_mens": "",
            "fl_ignorarbloqueioauto_recb": "",
            "id_endereco_sen": "",
            "id_forma_frecb": "",
            "st_marcador_recb": "",
            "fl_motivocancelar_recb": "",
            "fl_remessastatuscr_recb": "0",
            "id_formaboleto_frecb": "",
            "tx_remessamsg_recb": "",
            "id_adesao_plc": "",
            "st_motivocanceloutros_recb": "",
            "st_tokendaconta_recb": "",
            "nm_descontoatedia_recb": "",
            "ar_nomeformas_calc": "Boleto",
            "vl_valorcreditado_calc": "150.00",
            "id_pedido_ped": "13",
            "fl_conta_homologada": "2",
            "fl_cofre": "",
            "st_descricao_cb": "Principal",
            "tipo_conta": "",
            "nome_formatado": "<span class=cliente><i class=\"fa fa-user text-regular\"></i> <span class=id>1227</span> - <a href=http://sldeveloper.superlogica.net/clients/financeiro/sacados/id/1227?status=2 comportamentos=\"hint\" title=\"<span class=\'icon fa fa-calendar\'></span> &nbsp; Vencimento: 15\"><span class=nome>Nome Fantasia</span></a></span>",
            "publickey": "47e443b1583e5b03973aab095f07a8adcd16d964",
            "link_2via": "https://sldeveloper.superlogica.net/clients/areadocliente/publico/cobranca/c/-593-47e443b1583e5b03973aab095f07a8adcd16d964",
            "publickey_json": "265cf349bf4e44edf62d29937742489e669bafc9",
            "link_2via_json": "https://sldeveloper.superlogica.net/clients/areadocliente/publico/cobranca/c/-593-265cf349bf4e44edf62d29937742489e669bafc9-Json",
            "comconfirmacaoleitura": "",
            "acessovistoonline": "1",
            "descontovalorfixo": "",
            "msgdiasparadesconto": "Desconto para pagamento até o dia do vencimento",
            "descontoatedia": "",
            "vl_txdesconto_emp": "",
            "vl_txjuros_emp": "",
            "vl_txmulta_emp": "",
            "tx_bancaria": ""
        }', true);
    }
}